### ISSUE TITLE
You may like...

### ISSUE THREAD

**Issue by DakotaNelson** [evilsocket/sg1#2]
https://github.com/dakotanelson/sneaky-creeper might have some code that you can re-use, it appears to be very similar in structure.

It's in Python, though, so there'll be some porting, but it may at least inspire you.

Excited to see this project come together!

**Comment by evilsocket** [comment]
Dude!!!! You're writing those social modules that are channels for me too!! :D I'm writing pastebin channel right now, will surely reuse your stuff with proper crediting, thanks 👍
