### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by johnjohnsp1** [evilsocket/sg1#3]
Hello,

getting this output once I try to compile:

root@VMKALI20172:~/.go/src/github.com/evilsocket/sg1# make all
@ Building ...
# github.com/evilsocket/sg1/channels
channels/pastebin.go:134: undefined: sort.Slice
Makefile:11: recipe for target 'build' failed
make: *** [build] Error 2

did all steps within a Kali rolling 2017.2 using VMFusion and following the readme file any ideas ?

thanks

**Comment by evilsocket** [comment]
what's your `go version` ?

**Comment by johnjohnsp1** [comment]
root@VMKALI20172:~/.go/src/github.com/evilsocket/sg1/cmd/sg1# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/.go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build705677831=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

go1.7.5 linux/amd64

installed with apt-get install golang

**Comment by evilsocket** [comment]
go 1.8 is required
