### ISSUE TITLE
recent release build issue

### ISSUE THREAD

**Issue by johnjohnsp1** [evilsocket/sg1#5]
hello Simone,

updated go version to most recent release 1.9

root@VMKALI20173:~/go/src/github.com/evilsocket/sg1# go version
go version go1.9.2 linux/amd64

but when i type make:

root@VMKALI20173:~/go/src/github.com/evilsocket/sg1# make
@ Building sg1 ...
# command-line-arguments
./main.go:136:99: undefined: sg1.APP_BUILD_BRANCH
./main.go:136:121: undefined: sg1.APP_BUILD_DATE
Makefile:13: recipe for target 'sg1' failed
make: *** [sg1] Error 2

I can confirm until yesterday I had no problem or this issue on make

can you verify please ?

I have also a question that I don't understand:

when I type:

root@VMKALI20173:~/go/src/github.com/evilsocket/sg1/build# ./sg1 -in tls:0.0.0.0:8080
sg1 v1.0.0 ( built from master on 2017-11-24 15:22 for linux amd64 )

Generating new ECDSA certificate ...

  tls --> console

where I can find the files being generated ?

did a search but cannot find em

thanks

**Comment by evilsocket** [comment]
Did you clone the repo or did you just download the folder?

**Comment by johnjohnsp1** [comment]
Either with git clone or go get the error is the same 

Luca Grembo
