### ISSUE TITLE
Error when "Make"

### ISSUE THREAD

**Issue by cegi** [evilsocket/sg1#6]
Hi, thanks for the tool, i have Golang 1.9, followed your steps, when using "Make" i get : 
@ Building sg1 ...
# command-line-arguments
./main.go:136:91: undefined: sg1.APP_BUILD_DATE
Makefile:11: recipe for target 'sg1' failed
make: *** [sg1] Error 2

Any idea what i did wrong ? 

**EDIT :** The problem comes from the command "go get github.com/evilsocket/sg1/" i get the following message ;
 # github.com/evilsocket/sg1
/root/go/src/github.com/evilsocket/sg1/main.go:136:91: undefined: sg1.APP_BUILD_DATE

Any help appreciated, and thanks for the work.

**Comment by cegi** [comment]
Still not working...

**Comment by evilsocket** [comment]
Happy xmas! :D
